### ISSUE TITLE
Can't locate object method "_load_schema"

### ISSUE THREAD

**Issue by fsitedev** [tarantool/tarantool-perl#8] opened 2016-03-23 11:14 UTC
Reboot tarantool with working remote connections leads to error on the first request:

Can't locate object method "_load_schema" via package "Connection refused" (perhaps you forgot to load "Connection refused"?) at /usr/local/perl5.14/lib/site_perl/5.14.4/x86_64-linux/DR/Tarantool/MsgPack/AsyncClient.pm line 120

**Comment by Awety** [comment] 2016-03-23 11:21
Such an unusual case. Got it, I hope I'll deal with it during this week.

**Comment by Awety** [comment] 2016-04-04 07:49
I succeeded to reproduce this error in the following way: firewall tarantool port and then try to create connection object (using `DR::Tarantool::MsgPack::AsyncClient->connect(<...>, $cb)` method). When it tries to create a connection socket to the destination host:port it gets error `Connection refused` and should send (by design) that error as a string (not ref scalar) as the agrument to callback `&$cb`, but now it was broken :(. I fixed it (branch `correct_connfail_handle`, not in master yet, but today I'll merge it there): so if connection cannot be established `&$cb` gets error message as the argument.

In your case (restart tarantool server having connection established) you should get `Socket error` instead, I suppose.

**Comment by Awety** [comment] 2016-04-04 08:06
Merged into master.
```sh
$ git merge correct_connfail_handle --no-ff
Merge made by the 'recursive' strategy.
 Changes                                 |  7 +++++++
 README.md                               |  2 +-
 lib/DR/Tarantool/MsgPack/AsyncClient.pm | 18 ++++++++++--------
 3 files changed, 18 insertions(+), 9 deletions(-)
```

**Closed** 2016-04-04 08:06 UTC
